
  import type { Metadata } from "next";
  import { Inter } from "next/font/google";
  import "./globals.css";
  import { Providers } from "../redux/provider"; 
  import { store } from '../redux/store';

  const inter = Inter({ subsets: ["latin"] });

  export const metadata: Metadata = {
    title: "IPGLOBAL prueba técnica",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <Providers>{children}</Providers> 
        </body>
      </html>
    );
  }
